permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: cs50/jekyll-theme-cs50

title: ITI CS50

cs50:
  alert: warning dismissible
  description: ITI CS50 - Introduction to Computer Science

exclude:
  - manuals
  - vendor
